backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://northmelbourneweb.com/assets/svgs/logo-black.svg

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    
    - name: "portfolio"
      label: "Portfolio"
      folder: "src/content/portfolio"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Portfolio", the post will be accessible from "portfolio/portfolio-post"',
            }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Client", name: "client", widget: "string" }
          - { label: "Category", name: "category", widget: "list", default: ["Automation"] }
          - { label: "Industry", name: "industry", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Sub-title", name: "sub-title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Details Title 1", name: "details-title-1", widget: "string" }
          - { label: "Details Content 1", name: "details-content-1", widget: "string" }
          - { label: "Details Title 2", name: "details-title-2", widget: "string" }
          - { label: "Details Content 2", name: "details-content-2", widget: "string" }
          - { label: "Blockquote", name: "blockquote", widget: "string" }
          - { label: "Blockquote Author", name: "blockquote-author", widget: "string" }
          - { label: "Details Title 3", name: "details-title-3", widget: "string" }
          - { label: "Details Content 3", name: "details-content-3", widget: "string" }
          - { label: "Image 1", name: "image-1", widget: "image" }
          - { label: "Image 2", name: "image-2", widget: "image" }
          - { label: "Image 3", name: "image-3", widget: "image" }

